apiVersion: v1
kind: Secret
metadata:
  name: healthshift-secrets
type: Opaque
data:
  SUPABASE_URL: aHR0cHM6Ly93eW1scGRjYm1pZGl1Z3Jub21zcS5zdXBhYmFzZS5jbw
  SUPABASE_KEY: c2JfcHVibGlzaGFibGVfTUVSLVF1dkFRVjg2WWt5TjIxeS1UQV9QTl9IMnRZNg
