apiVersion: v1
kind: Secret
metadata:
  name: healthshift-secrets
type: Opaque
data:
  DATABASE_URL: postgresql://postgres:supersecretpassword@db.wymlpdcbmidiugrnomsq.supabase.co:5432/postgres
  SUPABASE_KEY: c2Jfc2VjcmV0XzMxSTdyZHdKaDNmYnNrdnlwWEtvWHdfZ3JZU2pQVzc=
